### ISSUE TITLE
Please add support for Bitcoin Lightning Donations

### ISSUE THREAD

**Issue by qnxdev** [SimpleMobileTools/Simple-Thank-You#103]
The people who love crypto are there because it helps them earn money

The people who love Bitcoin are there because they believe in freedom, open source, decentralisation and human rights.

Now we have a way to transact Bitcoin for instantly for free using Lightning network

It'll really help people to send you some love easily, whenever they feel like loving you : ) 

https://lightning.engineering/

**Comment by tibbi** [comment]
there are already 5 cryptos available, I dont plan adding more options there
