### ISSUE TITLE
Can SimpleMobileTools size be reduced?

### ISSUE THREAD

**Issue by malespiaut** [SimpleMobileTools/Simple-Thank-You#121]
Hello,

I'm a regular user of your applications, and I highly appreciate them.

I'm opening this issue and Simple Thank You as a general issue for Simple Mobile Tools.

I've always thought that the apps where a little too heavy for what they are. For instance, the Simple Thank You APK weights 7.3 MB, while having no practical use.

The Simple Calculator weights 7.3 MB as well, while other calculators are able to cut the size, sometimes more than half:

| Name | id | size |
| ---- | -- | ---- |
| OpenCalc | `com.darkempire78.opencalculator` | 4.8 MB |
| Calculator | `com.cyb3rg0d.calculator` | 2.8 MB |
| Unitto | `com.sadellie.unitto` | 2.7 MB |
| Clean Calculator | `home.jmstudios.calc` | 735 kB |

As a fun trivia, there's also an emulator of a scientific calculator, `com.cax.pmk.ext`, that weights only 270 kB.

Saving on space would reduce download time, bandwidth usage, and phone storage space. I'm not an Android expert, but I'm sure that something can be done to cut down some space, while keeping the same software quality.

Best regards.

**Comment by tibbi** [comment]
the apps are already tiny, doesnt make sense to make them even smaller
