### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Thank-You#19]
I guess, this app's only purpose is to be paid for? What sense does it make on F-Droid then?

**Comment by tibbi** [comment]
They dont have playstore, so its free there. Theres multiple ways of getting it for free anyway, so why not make it easier.

**Comment by OffifialMITX** [comment]
Does it mean you pushed it to F-Droid yourself?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tibbi** [comment]
ye sure
