### ISSUE TITLE
REQUEST: simple "kill all apps"

### ISSUE THREAD

**Issue by Benman2785** [SimpleMobileTools/Simple-Thank-You#25]
hi - i found you yesterday - already bought your "Dankeschön"

you actually do what most people need ;)

but i would need:
a "simple" APK that close/kills all running apps when its started (or to be able to set to do so) 

keep up your good work ;)

**Comment by tibbi** [comment]
Thanks :) I dont want to create such app though, it is highly discouraged to kill app from Recents. You should never use such app killers or memory cleaners. Also please for app suggestions use the left hand side button of https://simplemobiletools.github.io/ so people can vote on them.
