### ISSUE TITLE
Changing Icon-Color doesn't work

### ISSUE THREAD

**Issue by Termuellinator** [SimpleMobileTools/Simple-Thank-You#33]
First of all - thanks for your awesome apps! :+1: 
Unfortunately, changing the icon color doesn't work for me. Using Contacts, Gallery and Filemanager.
All installed via Playstore - i doubt installing via F-Droid would make a difference?
Reboot doesn't help. 
Also, the shared theme only partly works (have to go into each app and change to another theme and back to shared to have the changes take effect) - maybe related?
Using Resurrection Remix 6.2 (Android 8.1) on a Xiaomi Redmi Note 4. Launcher is Trebuchet.
Let me know what you need for further troubleshooting :)

**Comment by tibbi** [comment]
It is a launcher issue already reported at https://github.com/SimpleMobileTools/General-Discussion/issues/83, so the broken part in your case is Trebuchet. Try downloading some other launcher. Nova Launcher 5 works, but in the latest beta version 6 they broke it intentionally. Thanks

**Comment by Termuellinator** [comment]
Of course i didn't look at general discussion but the issues for every app ^^
Thanks for your quick answer!
It seems there is no bug filed for this @ https://jira.lineageos.org/issues - do you think it would be worth doing so?

**Comment by tibbi** [comment]
well you can try reporting it, at least they will give some feedback if they plan fixing it, or what. Let me know if they reply with something. Thanks

**Comment by tibbi** [comment]
so it is confirmed by now that icon changes are launcher issues. It is already reported at General Discussion too, as it affects all apps.
