### ISSUE TITLE
[All apps] Optimization for an OLED theme

### ISSUE THREAD

**Issue by AntoineD-dot-fr** [SimpleMobileTools/Simple-Thank-You#76]
Hello, as the application concerns all apps I did not know on which repository to create the issue.

**Context:**
I got used to a lot of apps with an OLED theme.
So black #000 on the background and on the header.

To change the color of the header in SimpleApps you have to change the main color.

**Problem :**
Except that black on black, it makes the titles and toggle invisible...
![](https://h.kher.nl/uploads/media_attachments/files/107/379/371/994/036/442/original/6e73cd686111ec64.png)

**Solution idea :**
Would it be possible to add a checkbox so that the header uses the background color and not the main color?
I think that this option would make usable an OLED theme and would allow to put a bright color in main color !

**Thanks a lot for all the work**

**Comment by tibbi** [comment]
settings have been remade already, make sure you use the latest app version. Thanks

**Comment by AntoineD-dot-fr** [comment]
I had indeed an update of callendar to make thanks.

But my request is still valid, at least I didn't find how to make the header black without having readability problems...

These screenshots are maybe more understandable

![Calendar](https://user-images.githubusercontent.com/1497894/144511809-6a5956ee-a7bf-4a01-8bb1-ba114104db19.png)
![Settings](https://user-images.githubusercontent.com/1497894/144511834-289b5672-ba12-4677-b84c-dd948d9d05de.png)

**Comment by AntoineD-dot-fr** [comment]
I showed the calendar app but the request is for all apps.

The idea would be to keep my green color as the main color, but just check a box to say "the header takes the background color"

By "header", I mean the top banner, not just the status bar

**Comment by tibbi** [comment]
well if you keep picking same colors you will sooner or later reach unreadable text. There is accent color a B&W theme for that reason, just use it.

**Comment by AntoineD-dot-fr** [comment]
@tibbi Ok, I didn't understand that this theme proposed this specificity.

Thanks a lot, it's perfect.
