### ISSUE TITLE
Monero donation support - XMR

### ISSUE THREAD

**Issue by sonalder-darlene** [SimpleMobileTools/Simple-Thank-You#83]
I would gladely donate if you accept Monero(XMR) donations.
Monero have advantages over BTC and ETH :

- Fast transactions
- Cheap/small fees
- Fungible
- More private and anonymous
- and more

See the [official website](https://getmonero.org) for more information about it.
It's quite popular in the privacy community which I think a large amount of your users are part of.
I really think Monero has a bright future as it's one of the best cryptocurrencies if not the best from a technical point. Also it officially released in 2014 so it's 8 years old, not a new crypto with no purpose of existing :P

**Comment by tibbi** [comment]
will take a look at it, created an issue at https://github.com/SimpleMobileTools/Simple-Thank-You/issues/83
